export const rawColors = {
  black_1: "#101010",
  white_1: "#FFFFFF",
  sandstone: "#F9F9F2",
  blue_1: "#4C607E",
  blue_2: "#172636",
  grey_1: "#35373B",
  grey_2: "#999999",
  grey_3: "#BDBDBD",
  grey_4: "#D5D5D5",
  grey_5: "#E0E0E0",
  grey_6: "#717171",
  grey_7: "#F6F6F6",
  red_1: "#910A2D",
  red_2: "#732728",
  red_3: "#E21C27",
  green_1: "#167332",
  yellow_1: "#F1C21B",
  yellow_2: "#FFF8E1",
  grey_rgb_1: "#6A7381",
} as const;

export default {
  text_primary: rawColors.black_1,
  text_secondary: rawColors.grey_1,
  text_tertiary: rawColors.grey_2,
  cta_primary: rawColors.red_1,
  cta_secondary: rawColors.red_2,
  background_white: rawColors.white_1,
  background_sandstone: rawColors.sandstone,
  background_blue_light: rawColors.blue_1,
  background_blue_dark: rawColors.blue_2,
  background_grey: rawColors.grey_7,
  default_form: rawColors.grey_4,
  disabled: rawColors.grey_3,
  divider: rawColors.grey_5,
  feedback_success: rawColors.green_1,
  feedback_error: rawColors.red_3,
  feedback_warning: rawColors.yellow_1,
  feedback_warning_background: rawColors.yellow_2,
  default_iconColor: rawColors.grey_1,
  default_iconColor_grey: rawColors.grey_6,
  shadow_1: rawColors.grey_rgb_1,
} as const;
